// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD-bUXHUpJcwvUokRsBoSpMmZCQ1U9Ch1A',
//     appId: '1:493335100398:web:aeb81bbfb4fbccfcf9ecff',
//     messagingSenderId: '493335100398',
//     projectId: 'note-f5631',
//     authDomain: 'note-f5631.firebaseapp.com',
//     storageBucket: 'note-f5631.firebasestorage.app',
//     measurementId: 'G-3TJQDMVDSZ',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBjzuo3Bu8asPc4u6IxrJQM8GpeG1nqVxQ',
//     appId: '1:493335100398:android:c712df11adf3457ff9ecff',
//     messagingSenderId: '493335100398',
//     projectId: 'note-f5631',
//     storageBucket: 'note-f5631.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDbh_PHbgN1Ox-CnZRIKTlujta6Ax-p6Zs',
//     appId: '1:493335100398:ios:fe2c7d245be7289ff9ecff',
//     messagingSenderId: '493335100398',
//     projectId: 'note-f5631',
//     storageBucket: 'note-f5631.firebasestorage.app',
//     iosBundleId: 'com.example.eitansela',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDbh_PHbgN1Ox-CnZRIKTlujta6Ax-p6Zs',
//     appId: '1:493335100398:ios:fe2c7d245be7289ff9ecff',
//     messagingSenderId: '493335100398',
//     projectId: 'note-f5631',
//     storageBucket: 'note-f5631.firebasestorage.app',
//     iosBundleId: 'com.example.eitansela',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyD-bUXHUpJcwvUokRsBoSpMmZCQ1U9Ch1A',
//     appId: '1:493335100398:web:42b1b37861ca6b4df9ecff',
//     messagingSenderId: '493335100398',
//     projectId: 'note-f5631',
//     authDomain: 'note-f5631.firebaseapp.com',
//     storageBucket: 'note-f5631.firebasestorage.app',
//     measurementId: 'G-M5QHT1Z7E6',
//   );
// }
